name: overlay_dialog
description: A Flutter package for showing platform dialogs without using new routes.
version: 0.0.2
author: Anastasia Artemyeva (anastasia.artemyeva@orioninc.com)
homepage: https://ctogitlab.mera.com/anartem/flutter-overlay-dialog

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
